export const GET_ALL_MATRIAL = "GET_ALL_MATRIAL";
export const GET_ERROR = "GET_ERROR"
export const ADD_MATRIAL = "ADD_MATRIAL"
export const DELETE_MATRIAL = "DELETE_MATRIAL"
export const GET_ALL_DEPARTMENTS = "GET_ALL_DEPARTMENTS"
export const GET_ALL_MATRIAL_PAGENAT = "GET_ALL_MATRIAL_PAGENAT"

export const GET_ALL_COURSES = "GET_ALL_COURSES"
export const ADD_COURSE ="ADD_COURSE"
export const DELETE_COURSE ="DELETE_COURSE"